"""
Sample microservice — generated by Walmart Platform Engineering.
This is a golden-path template used by the Internal Developer Portal.
"""
from flask import Flask, jsonify
import os

app = Flask(__name__)

SERVICE_NAME = os.getenv("SERVICE_NAME", "search-service")
VERSION = os.getenv("VERSION", "v1")

@app.route("/")
def index():
    return jsonify({
        "service": SERVICE_NAME,
        "version": VERSION,
        "status": "healthy"
    })

@app.route("/health")
def health():
    return jsonify({"status": "ok"}), 200

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8080)
